### ISSUE TITLE
Strange Incompatability

### ISSUE THREAD

**Issue by NoobChester** [jellysquid3/phosphor-fabric#13]
Crash log: https://paste.ee/p/5edGn
Log: https://paste.ee/p/nWzdE

Modlist:
1. https://github.com/PhiPro95/mc-fixes/releases/tag/lighting-fixes-v1.0.0
2. https://github.com/gudenau/minecraft-gudfps/releases/tag/v0.0.2
3. https://github.com/jellysquid3/phosphor-fabric/releases/tag/mc1.16.1-v0.6.0

Curseforge links for phosphor and gudFPS:
https://www.curseforge.com/minecraft/mc-mods/gudfps/files/3030046
https://www.curseforge.com/minecraft/mc-mods/phosphor/files/2987621

The crash only occurs when those three mods are all loaded, combinations like "1. 3." , "1. 2." , "2. 3." are fine.

**Comment by LucilleTea** [comment]
Phosphor and lighting-fixes are completely incompatible, and will crash upon joining a world (singleplayer or multiplayer).
Adding gudFPS makes the crash occur during startup, but I don't think that means much - it's only hitting the problem earlier because it loads the conflict earlier.

**Comment by NoobChester** [comment]
ok thank you, I will close this issue now.

**Comment by fdgonzalez781** [comment]
I posted a similar comment at mc-fixes, but I figured I'd post it here as well:

In my custom forks of mc-fixes and Phosphor, I was able to modify both mods so that they are mutually compatible on Minecraft 1.16.1.

So far, I have been able to play single player and multiplayer using Sodium, Lithum, Phosphor, and mc-fixes together. I'm not sure if the resulting lighting logic makes sense, but I have not observed any new lighting glitches or unexpected errors, and performance seems perfectly fine. I'm not sure if it makes sense to make a pull request since there are various hacky changes to Phosphor that I had to make, up to and including the use of Fabric-ASM, so I'll at least include my forks as a temporary fix for people who would like to use these mods together.

mc-fixes: https://github.com/the6thdoor/mc-fixes
Phosphor: https://github.com/the6thdoor/phosphor-fabric
