### ISSUE TITLE
Broken lighting in 1.16.5

### ISSUE THREAD

**Issue by googleooer** [jellysquid3/phosphor-fabric#43]
mod version: phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
other mods installed: fabric-api-0.30.3+1.16.jar, lithium-fabric-mc1.16.5-0.6.3.jar, sodium-fabric-mc1.16.3-0.1.0.jar, tic-tacs-0.1.2.jar

When I create a new world, sky lighting is completely broken. See attached images.
![image](https://user-images.githubusercontent.com/35429559/108580147-f9094900-7308-11eb-8785-bccb4184dd80.png)
![image](https://user-images.githubusercontent.com/35429559/108580152-ff97c080-7308-11eb-9528-c40c53cea4cb.png)

**Comment by LucilleTea** [comment]
The release version of tic-tacs (0.1.2) is incompatible with phosphor 0.7.x. This incompatibility has been fixed in tic-tacs development versions.
You will probably need to erase lighting data to fix the lighting glitch after you fix the mod conflict itself. In singleplayer you can use the optimize world feature and erase cached data.

**Comment by googleooer** [comment]
I see, thank you.
