### ISSUE TITLE
Support for 1.17?

### ISSUE THREAD

**Issue by saransh323** [jellysquid3/phosphor-fabric#54]
Will you consider updating Phosphor to 1.17, or is the mod not necessary anymore due to the rendering changes in 1.17?

**Comment by LucilleTea** [comment]
An update is planned and in progress, yes. No estimate, but you can [join the discord](https://caffeinemc.net/discord) for more information.

**Comment by molaeiali** [comment]
I don't understand why all other issues are marked as duplicates of this, and this is closed, shouldn't this one stay open until it resolves? Just for the record, I think this is the latest update on the issue since 09/09/2021: [discord](https://discord.com/channels/602796788608401408/602796788608401410/885566410724634625)
> We don't have an ETA as to when Phosphor for MC 1.17 will be available. There were some changes made in MC 1.17 with regards to the lighting engine that require Phosphor to be updated accordingly. It's not a straightforward port. Right now, we don't have any developer resources to tackle that with, so there aren't any updates in this channel.

**Comment by jellysquid3** [comment]
Issues which are marked as questions are almost always closed and directed to our Discord server. I thought we had a tracking issue for the MC 1.17 port, but it seems not.

**Comment by jellysquid3** [comment]
See #69.
