### ISSUE TITLE
doesn't work in 1.18.2

### ISSUE THREAD

**Issue by ech0nyx** [jellysquid3/phosphor-fabric#78]

**Comment by PhiProven** [comment]
Please provide a more sophisticated description of the issue. In particular, include a crash log.

**Comment by BD103** [comment]
Phosphor 0.8.1 is not published on Modrinth. This made me think that it didn't yet support 1.18. I have little-to-no knowledge when to comes to publishing mods, but I believe this (should) be an easy fix.

**Comment by PhiProven** [comment]
Ah. The `.x` in the version number means that it is supposed to work on all subversions of `1.18`. This is of course a bit speculative on future code changes, but usually works fine for Phosphor. So, unless stated otherwise, it can be expected to work.
Curseforge and Modrinth only allow to set individual versions, though, and I have now updated them.

**Comment by BD103** [comment]
Perfect!
